use_frameworks!

platform :ios, '8.0'

target 'TQ_Networking_Example' do
  pod 'TQ_Networking', :path => '../'

  target 'TQ_Networking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
